# Generated by Django 6.0.4 on 2026-04-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('targetCourse', models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Java Full Stack', 'Java Full Stack'), ('Python Development', 'Python Development'), ('MERN Stack', 'MERN Stack'), ('SQL & Data Analytics', 'SQL & Data Analytics')], max_length=100)),
                ('batchMonth', models.CharField(choices=[('All Batches', 'All Batches'), ('June Batch', 'June Batch'), ('Sept Batch', 'Sept Batch'), ('Dec Batch', 'Dec Batch')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('videoLink', models.URLField()),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('targetCourse', models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Java Full Stack', 'Java Full Stack'), ('Python Development', 'Python Development'), ('MERN Stack', 'MERN Stack'), ('SQL & Data Analytics', 'SQL & Data Analytics')], max_length=100)),
                ('batchMonth', models.CharField(choices=[('All Batches', 'All Batches'), ('June Batch', 'June Batch'), ('Sept Batch', 'Sept Batch'), ('Dec Batch', 'Dec Batch')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('driveLink', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('targetCourse', models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Java Full Stack', 'Java Full Stack'), ('Python Development', 'Python Development'), ('MERN Stack', 'MERN Stack'), ('SQL & Data Analytics', 'SQL & Data Analytics')], max_length=100)),
                ('batchMonth', models.CharField(choices=[('All Batches', 'All Batches'), ('June Batch', 'June Batch'), ('Sept Batch', 'Sept Batch'), ('Dec Batch', 'Dec Batch')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
